// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import { loadEnv as loadDotEnvFiles } from 'vite';
import { loadEnv, pickEnvValue } from './src/config/env';

/**
 * `astro.config.ts` is loaded by Astro's own config loader, a separate,
 * earlier phase than the app's Vite pipeline — its module context never
 * populates `import.meta.env`, and env vars from a local `.env` file
 * (loaded later, only for the app build/dev server) aren't available yet
 * either. `site` is resolved here by calling `../src/config/env`'s
 * `loadEnv(source)` directly against `process.env` — the exact same
 * absolute-HTTP(S)/trailing-slash validation the rest of the app uses for
 * `SITE_URL` — rather than hand-rolling a second, independent URL check
 * that could drift from it over time.
 *
 * (`loadEnv` — the plain, non-eager function — is safe to import here even
 * though it lives alongside the eagerly-exported `env` singleton: `env` is
 * now a lazily-computed Proxy that only validates on first property
 * access, so merely importing this module has no side effect. See
 * `src/config/env.ts` for why that matters.)
 *
 * `loadEnv` requires both `WORDPRESS_URL` and `SITE_URL`, but only
 * `siteUrl` is used here, so a placeholder `WORDPRESS_URL` is substituted
 * when it isn't set yet (config-load time doesn't need it) purely to
 * satisfy `loadEnv`'s contract.
 *
 * Because this phase runs before Astro loads `.env` for the app, `SITE_URL`
 * is read from BOTH sources explicitly: Vite's `loadEnv` reads the `.env`
 * files directly, and real `process.env` values take precedence over them —
 * the same precedence Vite/Astro apply for the app itself. Without this, a
 * `SITE_URL` set only in `.env` (the documented quick start) would be
 * invisible here and `site` would silently fall back to the placeholder,
 * emitting a sitemap full of `example.com` URLs while the app's own
 * canonical tags used the real host.
 *
 * The placeholder is used ONLY when `SITE_URL` is genuinely absent from both
 * sources, so config loading (and therefore `npm run typecheck` / `npm run
 * lint`) keeps working with zero env vars set — and it warns when it does,
 * so a misconfigured build is never silent. A `SITE_URL` that IS set but
 * invalid is never swallowed: `loadEnv` throws and the build fails loudly.
 */
const PLACEHOLDER_SITE_URL = 'https://example.com';

function resolveSiteUrl(): string {
  // Prefix '' loads every variable, not just Vite's public `VITE_`-prefixed ones.
  const fileEnv = loadDotEnvFiles(process.env.NODE_ENV ?? 'production', process.cwd(), '');
  const siteUrl = pickEnvValue('SITE_URL', process.env, fileEnv);
  const wordpressUrl = pickEnvValue('WORDPRESS_URL', process.env, fileEnv);

  if (!siteUrl) {
    console.warn(
      `[astro.config] SITE_URL is not set (checked process.env and .env files) — falling back to the placeholder "${PLACEHOLDER_SITE_URL}". ` +
        'Any sitemap generated by this build will reference that placeholder host. Set SITE_URL before building for deployment.',
    );
    return PLACEHOLDER_SITE_URL;
  }

  return loadEnv({
    WORDPRESS_URL: wordpressUrl ?? 'https://placeholder.invalid',
    SITE_URL: siteUrl,
  }).siteUrl.href;
}

// https://astro.build/config
export default defineConfig({
  site: resolveSiteUrl(),
  integrations: [sitemap()],
});
